name: DEV-CICD

on: 
  push:
    branches:
      - dev

env:
  TARGETARCH: amd64
  TARGETENV: dev

jobs:
  ci:
    name: DEV-CICD
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Run test
      run: make test
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: qa
        FOLDER: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
